title: Yelp Star Rating Predictor
description: This project aims to use a restaurant's yelp data in order to predict the how many stars it will recieve test
authors: Ishita Date, Nandin Padheriya, and Prithvi Rathaur 
theme: jekyll-theme-cayman
